version: '3.6'

services:

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'expenses_app'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - /tmp:/var/lib/mysql

  expenses-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EXPENSES_API_VERSION=1.1.1
    depends_on:
      - db
    environment:
      - PROFILE=prod
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_PORT=3307
    ports:
      - 8081:8081

