apiVersion: v1
kind: Service
metadata:
  name: expensesapp-service
spec:
  selector:
    app: app 
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
